apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: team-notebook-2
  namespace: rhods-project
spec:
  template:
    spec:
      containers:
        - name: team-notebook-2
          image: pytorch-gpu
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
