apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: team-notebook-1
  namespace: rhods-project
spec:
  template:
    spec:
      containers:
        - name: team-notebook-1
          image: s2i-minimal-notebook
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
