apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - patch-notebook.yaml
  - patch-runtime.yaml

commonLabels:
  rhods-group: data-scientists
