apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: team-notebook-1
spec:
  template:
    spec:
      containers:
        - name: team-notebook-1
          resources:
            limits:
              cpu: "4"
              memory: "16Gi"
