apiVersion: v1
kind: Secret
metadata:
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/display-name: s3-minio
  name: s3-minio
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: any
  AWS_S3_ENDPOINT: http://minio-minio.apps.ocp4.example.com
  AWS_S3_BUCKET: models-bucket
  AWS_SECRET_ACCESS_KEY: minio123
