apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhods-project-admin
  namespace: rhods-project
subjects:
- kind: Group
  name: data-scientists
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
