apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${NAMESPACE}-admin
  namespace: ${NAMESPACE}
subjects:
- kind: ${SUBJECT_KIND}
  name: ${OWNER}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ${RBAC_ROLE}
  apiGroup: rbac.authorization.k8s.io
