apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: ${NOTEBOOK_NAME}
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      containers:
      - name: ${NOTEBOOK_NAME}
        image: ${NOTEBOOK_IMAGE}
        resources: ${NOTEBOOK_RESOURCES}
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: ${NOTEBOOK_NAME}-pvc
      volumes:
      - name: ${NOTEBOOK_NAME}-pvc
        persistentVolumeClaim:
          claimName: ${NOTEBOOK_NAME}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NOTEBOOK_NAME}-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_SIZE}
